# Project Euler, Problem 29.
# By Espen Sales
# 25/10/2018

maxa = 100
maxib = 100

abintecom = []

for a in range(2,maxa+1):
    for b in range(2,maxib+1):
        abintecom.append(a**b)
        print(a,"of",maxa)
        
abinteset = set(abintecom)

print()
print("There are",len(abinteset),"distinct terms in the sequence generated by a^b for which 2<=a<"+str(maxa),"and 2<=b<="+str(maxib))
        
        



